def checkout(String repoPrefix, String repoSuffix = '', String updaterClass = 'UpdateUpdater') {
  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'gradle',
  remote: "${repoPrefix}/gradle${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'vectoraccount',
  remote: "${repoPrefix}/vectoraccount${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'vectoraccount-ejb',
  remote: "${repoPrefix}/vectoraccount-ejb${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'vectorapp',
  remote: "${repoPrefix}/vectorapp${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'vectorcommon',
  remote: "${repoPrefix}/vectorcommon${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'vectorexception',
  remote: "${repoPrefix}/vectorexception${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'vectorpersistence',
  remote: "${repoPrefix}/vectorpersistence${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'vectorsiebelgateway',
  remote: "${repoPrefix}/vectorsiebelgateway${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'vectorutil',
  remote: "${repoPrefix}/vectorutil${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'vectorweb',
  remote: "${repoPrefix}/vectorweb${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'vectorwsweb',
  remote: "${repoPrefix}/vectorwsweb${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'static_pages/flcss',
  remote: "${repoPrefix}/static_pages/flcss${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])

  checkout([$class: 'SubversionSCM',
  additionalCredentials: [],
  excludedCommitMessages: '',
  excludedRegions: '',
  excludedRevprop: '',
  excludedUsers: '',
  filterChangelog: false,
  ignoreDirPropChanges: false,
  includedRegions: '',
  locations: [[credentialsId: 'fa7413da-bf54-4edd-8388-98e2794a4fca',
  depthOption: 'infinity',
  ignoreExternalsOption: true,
  local: 'eCustomer',
  remote: "${repoPrefix}/eCustomer${repoSuffix}"]],
  workspaceUpdater: [$class: updaterClass]])
}
return this
