document.write('<div class="footerEnvelope">')
	document.write('<div class="footerBlock" style="margin-right: 50px;"><img src="../images/fastrak_logo.png" style="margin-bottom: 50px;"></div>')
	document.write('<div class="footerBlock">')
		document.write('<div class="footerTitle">SITEMAP</div>');
		document.write('<div>')
		document.write('<A href="../home/index.shtml" class="footerLink">Home</a><BR>')
		document.write('<A href="../howitworks/3_easySteps.shtml" class="footerLink">Three Easy Steps</a>')
		document.write('</div>')
	document.write('</div>')
	document.write('<div class="footerBlock">')
		document.write('<div class="footerTitle">ABOUT US</div>')
		document.write('<div>')
		document.write('<A href="../about/agencies.shtml" class="footerLink">Agencies & Partners</a><BR>')
		document.write('<A href="../about/news.shtml" class="footerLink">News</a>')
		document.write('</div>')
	document.write('</div>')
	document.write('<div class="footerBlock">')
		document.write('<div class="footerTitle">SUPPORT</div>')
		document.write('<div>')
		document.write('<a href="../support/faqs.shtml" class="footerLink">FAQs</a><BR>')
		document.write('<A href="../support/feedback.shtml" class="footerLink">Feedback</a><br>')
		document.write('<A href="../support/contactUs.shtml" class="footerLink">Contact Us</a>')
		document.write('</div>')
	document.write('</div>')
	document.write('<div class="footerBlock">')
		document.write('<div class="footerTitle">FOLLOW US</div>')
		document.write('<div><a href="http://www.facebook.com/BayAreaFastrak" target="_blank"><img src="../images/facebookLogo.png" border="0"></a></div>')
	document.write('</div>')
	document.write('<div class="footerCopyright">&copy; 2015 FasTrak &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="../support/termsofuse.shtml" class="footerLink">Terms Of Use</a> &nbsp; | &nbsp; <a href="../support/privacy.shtml" class="footerLink">Terms & Security</a></div>')
document.write('</div>')

